- name: Apply EEPROM config
  become: true
  ansible.builtin.command: rpi-eeprom-update -d -f /tmp/bootconf.txt
  register: eeprom_apply
  delegate_to: "{{ hostname_map[item] }}"
  loop: "{{ nodes_list }}"
  loop_control:
    loop_var: node
  changed_when: "'*** INSTALL' in (eeprom_apply.stdout | default(''))"
  failed_when: eeprom_apply.rc != 0
