---
- name: Ensure all unsaved data is flushed to disk
  ansible.builtin.command: sync
  changed_when: false

- name: Shutdown worker nodes
  ansible.builtin.command: /sbin/shutdown -h now
  become: true
  async: 0
  poll: 0
  changed_when: true
  failed_when: false
