---
- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml

- name: Include brick node tasks
  ansible.builtin.import_tasks: brick_node.yml
  when: inventory_hostname in groups[gluster_bricks_group]

- name: Include control node tasks
  ansible.builtin.import_tasks: control_node.yml
  run_once: true
  when: inventory_hostname == groups[gluster_bricks_group][0]

- name: Include mount volume tasks
  ansible.builtin.import_tasks: mount_volume.yml
