---
- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml

- name: Include brick node tasks
  ansible.builtin.import_tasks: brick_node.yml
  when: inventory_hostname == gluster_brick_node

- name: Include control node tasks
  ansible.builtin.import_tasks: control_node.yml
  when: inventory_hostname in groups['control']

- name: Include mount volume tasks
  ansible.builtin.import_tasks: mount_volume.yml
