- name: Install GlusterFS packages
  ansible.builtin.apt:
    name: ["glusterfs-server", "glusterfs-client"]
    state: present
    update_cache: true

- name: Ensure GlusterFS service is enabled and started
  ansible.builtin.systemd:
    name: glusterd
    enabled: true
    state: started
