- name: Copy temperature exporter script
  ansible.builtin.template:
    src: temperature_exporter.sh.j2
    dest: /usr/local/bin/temperature.sh
    mode: '0755'
    owner: root
    group: root

- name: Add cron job to export CPU temperature
  ansible.builtin.cron:
    name: "Export RPi CPU temperature"
    user: "{{ node_exporter_user }}"
    job: "/usr/local/bin/temperature.sh"
    minute: "*/1"
