- name: Create secret for Grafana SMTP password
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-smtp-secret
        namespace: "{{ helm_namespace }}"
      type: Opaque
      stringData:
        GRAFANA_SMTP_PASSWORD: "{{ grafana_smtp_password }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
