---
ssh_key_type: "ed25519"
ssh_key_bits: 4096 # only used if type is rsa
ssh_key_comment: "raspi-cluster"
ssh_connection_timeout: 10
ssh_private_key_file: "id_{{ ssh_key_type }}_cluster"
ssh_public_key_file: "id_{{ ssh_key_type }}_cluster.pub"
ssh_private_key_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_private_key_file }}"
ssh_public_key_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_public_key_file }}"
ssh_known_hosts: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey"
