gluster_namespace: default
gluster_pv_name: gluster-pv
gluster_pvc_name: gluster-pvc
gluster_storage_class_name: gluster-static
gluster_static_pv_size: 1Gi
gluster_access_mode: ReadWriteMany
gluster_hostpath: /mnt/glusterfs-volume
gluster_node_name: rpi-node0
gluster_deployment_name: gluster_deploy