- name: Create manifests directory for k3s
  ansible.builtin.file:
    path: "{{ kube_manifests_dir }}"
    state: directory
    owner: k3sadmin
    group: k3sadmin
    mode: '0755'

- name: Copy Grafana ingress manifest
  ansible.builtin.template:
    src: "grafana_ingress.yaml.j2"
    dest: "{{ kube_manifests_dir }}/grafana_ingress.yaml"
    owner: k3sadmin
    group: k3sadmin
    mode: '0644'

- name: Copy Prometheus ingress manifest
  ansible.builtin.template:
    src: "prometheus_ingress.yaml.j2"
    dest: "{{ kube_manifests_dir }}/prometheus_ingress.yaml"
    owner: k3sadmin
    group: k3sadmin
    mode: '0644'

- name: Apply ingress resources
  kubernetes.core.k8s:
    state: present
    src: "{{ kube_manifests_dir }}/{{ item | basename }}"
  loop:
    - grafana_ingress.yaml
    - prometheus_ingress.yaml
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
