---
- name: Include monitoring setup prereqs
  ansible.builtin.import_tasks: setup_prereqs.yml

- name: Install and configure Prometheus
  ansible.builtin.import_tasks: prometheus_install.yml

- name: Install and configure Grafana
  ansible.builtin.import_tasks: grafana_install.yml

- name: Install and configure Traefik Ingress Controller
  ansible.builtin.import_tasks: traefik_install.yml

- name: Setup ingress for Traefik
  ansible.builtin.import_tasks: ingress_config.yml
