---
- name: Include Docker setup prereqs
  ansible.builtin.include_tasks: setup_prereqs.yml

- name: Include Docker repository configuration
  ansible.builtin.include_tasks: configure_repo.yml

- name: Include Docker installation
  ansible.builtin.include_tasks: install_docker.yml

- name: Include post-install configuration
  ansible.builtin.include_tasks: post_install.yml
