nvme_format: false                          # Whether to format the NVMe device before provisioning
                                            # (set to false to skip formatting step)
nvme_nodes: []                              # [] means “all nodes in nvme_map”
nvme_slot: "a"                              # valid values: "a", "b"

image_cache_dir: "/mnt/downloads/os_images" # Download directory where all images are cached on node0
