nvme_format: false        # Whether to format the NVMe device before provisioning
                          # (set to false to skip formatting step)

image_cache_dir: "/mnt/downloads/os_images" # Download directory where all images are cached on node0
