nvme_device: "/dev/nvme0n1"   # default NVMe device
nvme_nodes: []                # [] means “all nodes in nvme_partitions”
nvme_slot: "A"                # valid values: "A", "B"
nvme_format: no

# Partition map
nvme_partitions:
  node0:
    A: { boot: 1, root: 2 }
    B: { boot: 3, root: 4 }
  node1:
    A: { boot: 5, root: 6 }
    B: { boot: 7, root: 8 }
  node2:
    A: { boot: 9, root: 10 }
    B: { boot: 11, root: 12 }
  node3:
    A: { boot: 13, root: 14 }
    B: { boot: 15, root: 16 }

# Download directory where all images are cached on node0:
image_cache_dir: "/mnt/downloads/os_images"
