# PXE boot configuration
pxe_interface: eth0
pxe_proxy_network: "192.168.100.0"
pxe_subnet_mask: "255.255.255.0"

pxe_nfs_host: "node0"         # control node on whitch nfs/tftp mounts are performed

nfs_base: "/srv/nfs"          # NFS base mount point
tftp_base: "/srv/tftp"        # TFTP base mount point

bootfs_fstype: "vfat"         # BOOT partition filesystem
rootfs_fstype: "ext4"         # ROOT partition filesystem

bootfs_opts: "defaults"
rootfs_opts: "defaults"

part_list: []                 # List of NVMe partitions based on selected nodes and active slots

# TFTP configuration
tftp_dir: /srv/tftp           # TFTP base mount point

# NFS configuration
nfs_root_dir: /srv/nfs        # NFS base mount point
