---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
    state: present

- name: Ensure Python3 and pip3 are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Download and install k3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start k3s service
  ansible.builtin.systemd:
    name: k3s
    enabled: yes
    state: started

- name: Install Kubernetes Python client library
  ansible.builtin.shell: pip3 install kubernetes --break-system-packages
  args:
    warn: false

- name: Install kubectl binary using curl
  ansible.builtin.command: >
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/arm64/kubectl
    && chmod 755 kubectl
    && sudo mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl
  register: kubectl_download

# - name: Install kubectl binary
#   ansible.builtin.get_url:
#     url: https://dl.k8s.io/release/v1.29.2/bin/linux/arm64/kubectl
#     dest: /usr/local/bin/kubectl
#     mode: '0755'
#   register: kubectl_download

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_version
  changed_when: false

- name: Display installed kubectl version
  ansible.builtin.debug:
    msg: "{{ kubectl_version.stdout }}"

- name: Create kubeconfig directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy kubeconfig for user
  ansible.builtin.copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    remote_src: true

- name: Update kubeconfig server address
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.kube/config"
    regexp: '^    server:'
    line: '    server: https://{{ ansible_host }}:6443'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
