---
- name: Configure cgroup settings
  ansible.builtin.include_tasks: cgroup.yml

- name: Install K3S on control nodes
  ansible.builtin.include_tasks: install_control.yml
  when: "'control' in group_names"

- name: Join worker nodes to cluster
  ansible.builtin.include_tasks: install_workers.yml
  when: "'workers' in group_names"
