---
- name: Check if Docker service exists
  ansible.builtin.shell: systemctl is-active docker
  register: docker_service_status
  ignore_errors: yes

- name: Stop Docker service if it is active
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: no
  when: docker_service_status.rc == 0

- name: Check if containerd service exists
  ansible.builtin.shell: systemctl is-active containerd
  register: containerd_service_status
  ignore_errors: yes

- name: Stop containerd service if it is active
  ansible.builtin.systemd:
    name: containerd
    state: stopped
    enabled: no
  when: containerd_service_status.rc == 0

- name: Remove Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
    purge: yes

- name: Remove Docker's official GPG key
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Cleanup unused dependencies
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes
    update_cache: yes

- name: Remove Docker directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/docker
    - /etc/apt/
    - /var/run/docker.sock

- name: Verify Docker is removed
  ansible.builtin.command: docker --version
  register: docker_version
  ignore_errors: yes

- name: Show Docker version output
  debug:
    var: docker_version.stdout
