---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check if Docker service exists
  ansible.builtin.set_fact:
    docker_service_status: "{{ 'docker.service' in services }}"

- name: Stop Docker service if it is active
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: false
  when: docker_service_status.rc == 0

- name: Check if containerd service exists
  ansible.builtin.set_fact:
    containerd_service_status: "{{ 'containerd.service' in services }}"

- name: Stop containerd service if it is active
  ansible.builtin.systemd:
    name: containerd
    state: stopped
    enabled: false
  when: containerd_service_status.rc == 0

- name: Remove Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
    purge: true

- name: Remove Docker's official GPG key
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Cleanup unused dependencies
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
    update_cache: true

- name: Remove Docker directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/docker
    - /etc/apt/
    - /var/run/docker.sock

- name: Verify Docker is removed
  ansible.builtin.command: docker --version
  register: docker_version
  ignore_errors: true
  changed_when: false

- name: Show Docker version output
  ansible.builtin.debug:
    var: docker_version.stdout
