---
ansible_python_interpreter: /usr/bin/python3

nvme_device: "/dev/nvme0n1"   # NVMe device that holds all per-node partitions

nvme_map:                     # mapping of logical nodes to physical NVMe devices
  node0:
    a: { boot: 1, root: 2 }
    b: { boot: 3, root: 4 }
  node1:
    a: { boot: 5, root: 6 }
    b: { boot: 7, root: 8 }
  node2:
    a: { boot: 9, root: 10 }
    b: { boot: 11, root: 12 }
  node3:
    a: { boot: 13, root: 14 }
    b: { boot: 15, root: 16 }

boot_map:
  node0:
    boot_mode: nvme_prio
  node1:
    boot_mode: net_prio
  node2:
    boot_mode: net_prio
  node3:
    boot_mode: net_prio

hostname_map:
  node0: rpi-node0
  node1: rpi-node1
  node2: rpi-node2
  node3: rpi-node3
  
helm_namespace: monitoring    # default namespace for Helm and Kubernetes operations
helm_release: monitor-stack   # default Helm release name for Prometheus and Grafana
