$ANSIBLE_VAULT;1.1;AES256
63373230356631303965643366356436326464346431313832386362663761623063643834633933
3230373637666438326461623666336231303634303463390a376162336463303738343339356430
61643933363834666466666230376135626637306262626361383337633662626466636363346434
3262383861656263630a313163623033393462303535323436646564376634323062366232356339
64346536333163363363373639646530643264313638646531656366626231626166303761633237
66646635643537396530623663626338396139623861623434353365626233396530323166353264
33393561393837613265303432666563663730646136336261303332633338326232363166336563
61313039333665666634
