- name: Check parameters
  ansible.builtin.import_tasks: check_params.yml

- name: Format NVMe device
  ansible.builtin.import_tasks: nvme_format.yml

- name: Include flashing tasks
  ansible.builtin.import_tasks: nvme_provision.yml
