---
- name: Shutdown entire cluster safely
  hosts: cluster
  become: true
  gather_facts: false
  serial: 1

  roles:
    - cluster_shutdown

  # Shutdown cluster nodes.
  # Example command line to run this playbook:
  # ansible-playbook playbooks/cluster_shutdown.yml
  # TODO: add parameter -e nodes=node0,node1
