---
- name: Setup GlusterFS
  hosts: cluster
  become: true
  gather_facts: true

  roles:
    - glusterfs_install

- name: Expose GlusterFS to Kubernetes
  hosts: control
  become: true
  roles:
    - k3s_glusterfs
