---
- name: Install K3S cluster
  hosts: cluster
  become: true
  gather_facts: false

  roles:
    - k3s_install

  # Example command line to run this playbook:
  # ansible-playbook playbooks/k3s_install.yml -i inventories/production/hosts
