---
- name: Cluster monitoring installation
  hosts: control
  become: true
  vars_files:
    - ../inventories/production/group_vars/all/vault.yml
    
  roles:
    - monitoring_install

  # Install monitoring stack components such as Prometheus, Grafana, and ingress.
  # Example command line to run this playbook:
  # ansible-playbook -i inventories/production/hosts playbooks/monitoring_install.yml
