---
- name: Configure cluster routing
  hosts: cluster
  become: true
  gather_facts: true

  roles:
    - role: network_setup

  # Example command line to run this playbook:
  # ansible-playbook -i inventories/production/hosts playbooks/network_setup.yml
