---
- name: Setup SSH configuration on localhost
  hosts: local
  become: false
  gather_facts: true
  roles:
    - compatibility
    - ssh_config

- name: Configure sshd on cluster nodes
  hosts: cluster
  become: true
  gather_facts: false
  roles:
    - ssh_config
