---
- name: Switch port control
  hosts: switch
  gather_facts: false

  vars:
    ntgrrc_bin: "{{ playbook_dir }}/../roles/switch_control/files/ntgrrc"
    poe_action: null          # Options: enable, disable, toggle
    configure_switch: false   # Set port names, speed, PoE policies, etc.

  roles:
    - switch_control

  # Control switch ports (enable/disable PoE, configure ports, etc.).
  # Example command to enable PoE on port 3:
  # ansible-playbook playbooks/switch_control.yml -e poe_action=enable
  # Example command to configure the switch:
  # ansible-playbook playbooks/switch_control.yml -e configure_switch=true
