- name: Check parameters for valid nodes
  ansible.builtin.import_role:
    name: params_check
    tasks_from: node_check.yml

- name: Check parameters for boot mode
  ansible.builtin.import_role:
    name: params_check
    tasks_from: bootmode_check.yml
