- name: Setup ssh on localhost and distribute keys to cluster nodes
  ansible.builtin.import_tasks: controller_keys.yml
  when: inventory_hostname in groups['local']

- name: Install SSH key and configure passwordless SSH
  ansible.builtin.import_tasks: nodes_sshd.yml
  when: inventory_hostname in groups['cluster']